# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import predict_pb2 as predict__pb2


class ModelServingStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predict = channel.unary_unary(
                '/model_serving.ModelServing/predict',
                request_serializer=predict__pb2.ModelInput.SerializeToString,
                response_deserializer=predict__pb2.ModelOutput.FromString,
                )
        self.reset = channel.unary_unary(
                '/model_serving.ModelServing/reset',
                request_serializer=predict__pb2.Empty.SerializeToString,
                response_deserializer=predict__pb2.Empty.FromString,
                )


class ModelServingServicer(object):
    """Missing associated documentation comment in .proto file"""

    def predict(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reset(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predict': grpc.unary_unary_rpc_method_handler(
                    servicer.predict,
                    request_deserializer=predict__pb2.ModelInput.FromString,
                    response_serializer=predict__pb2.ModelOutput.SerializeToString,
            ),
            'reset': grpc.unary_unary_rpc_method_handler(
                    servicer.reset,
                    request_deserializer=predict__pb2.Empty.FromString,
                    response_serializer=predict__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_serving.ModelServing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelServing(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model_serving.ModelServing/predict',
            predict__pb2.ModelInput.SerializeToString,
            predict__pb2.ModelOutput.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model_serving.ModelServing/reset',
            predict__pb2.Empty.SerializeToString,
            predict__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
