# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='predict.proto',
  package='model_serving',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rpredict.proto\x12\rmodel_serving\"@\n\nWindowMeta\x12\x13\n\x0bstart_frame\x18\x01 \x01(\x04\x12\x11\n\tend_frame\x18\x02 \x01(\x04\x12\n\n\x02id\x18\x03 \x01(\x04\"d\n\nModelInput\x12.\n\x0bwindow_meta\x18\x01 \x01(\x0b\x32\x19.model_serving.WindowMeta\x12\x12\n\ninput_data\x18\x02 \x03(\x0c\x12\x12\n\ninput_size\x18\x03 \x01(\x0c\"g\n\x0bModelOutput\x12.\n\x0bwindow_meta\x18\x01 \x01(\x0b\x32\x19.model_serving.WindowMeta\x12\x13\n\x0boutput_data\x18\x02 \x01(\x0c\x12\x13\n\x0boutput_size\x18\x03 \x01(\x0c\"\x07\n\x05\x45mpty2\x89\x01\n\x0cModelServing\x12\x42\n\x07predict\x12\x19.model_serving.ModelInput\x1a\x1a.model_serving.ModelOutput\"\x00\x12\x35\n\x05reset\x12\x14.model_serving.Empty\x1a\x14.model_serving.Empty\"\x00\x62\x06proto3'
)




_WINDOWMETA = _descriptor.Descriptor(
  name='WindowMeta',
  full_name='model_serving.WindowMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_frame', full_name='model_serving.WindowMeta.start_frame', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_frame', full_name='model_serving.WindowMeta.end_frame', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='model_serving.WindowMeta.id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=96,
)


_MODELINPUT = _descriptor.Descriptor(
  name='ModelInput',
  full_name='model_serving.ModelInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='window_meta', full_name='model_serving.ModelInput.window_meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_data', full_name='model_serving.ModelInput.input_data', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_size', full_name='model_serving.ModelInput.input_size', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=198,
)


_MODELOUTPUT = _descriptor.Descriptor(
  name='ModelOutput',
  full_name='model_serving.ModelOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='window_meta', full_name='model_serving.ModelOutput.window_meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_data', full_name='model_serving.ModelOutput.output_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_size', full_name='model_serving.ModelOutput.output_size', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=303,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='model_serving.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=312,
)

_MODELINPUT.fields_by_name['window_meta'].message_type = _WINDOWMETA
_MODELOUTPUT.fields_by_name['window_meta'].message_type = _WINDOWMETA
DESCRIPTOR.message_types_by_name['WindowMeta'] = _WINDOWMETA
DESCRIPTOR.message_types_by_name['ModelInput'] = _MODELINPUT
DESCRIPTOR.message_types_by_name['ModelOutput'] = _MODELOUTPUT
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WindowMeta = _reflection.GeneratedProtocolMessageType('WindowMeta', (_message.Message,), {
  'DESCRIPTOR' : _WINDOWMETA,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:model_serving.WindowMeta)
  })
_sym_db.RegisterMessage(WindowMeta)

ModelInput = _reflection.GeneratedProtocolMessageType('ModelInput', (_message.Message,), {
  'DESCRIPTOR' : _MODELINPUT,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:model_serving.ModelInput)
  })
_sym_db.RegisterMessage(ModelInput)

ModelOutput = _reflection.GeneratedProtocolMessageType('ModelOutput', (_message.Message,), {
  'DESCRIPTOR' : _MODELOUTPUT,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:model_serving.ModelOutput)
  })
_sym_db.RegisterMessage(ModelOutput)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:model_serving.Empty)
  })
_sym_db.RegisterMessage(Empty)



_MODELSERVING = _descriptor.ServiceDescriptor(
  name='ModelServing',
  full_name='model_serving.ModelServing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=315,
  serialized_end=452,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='model_serving.ModelServing.predict',
    index=0,
    containing_service=None,
    input_type=_MODELINPUT,
    output_type=_MODELOUTPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='reset',
    full_name='model_serving.ModelServing.reset',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELSERVING)

DESCRIPTOR.services_by_name['ModelServing'] = _MODELSERVING

# @@protoc_insertion_point(module_scope)
